# Generated by Django 4.0 on 2021-12-19 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegoZestawy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa producta')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cena')),
                ('type_product', models.CharField(max_length=255, verbose_name='Typ productu')),
                ('Marka', models.CharField(max_length=255, verbose_name='Marka productu')),
                ('Age', models.CharField(max_length=255, verbose_name='Przedział wiekowy')),
                ('Material', models.CharField(max_length=255, verbose_name='Material productu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Kategoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegoFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa producta')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('description', models.TextField(null=True, verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Cena')),
                ('type_product', models.CharField(max_length=255, verbose_name='Typ productu')),
                ('Marka', models.CharField(max_length=255, verbose_name='Marka productu')),
                ('Age', models.CharField(max_length=255, verbose_name='Przedział wiekowy')),
                ('Material', models.CharField(max_length=255, verbose_name='Material productu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Kategoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
